### ISSUE TITLE
Hi Author ， what‘s the meaning of CI and BI.

### ISSUE THREAD

**Issue by micyan01** [pcineverdies/FFT-AVX-512#1]

**Comment by pcineverdies** [comment]
Hi, I suggest you to read [the original article](https://www.researchgate.net/publication/370393863_Experiments_on_Speeding_Up_the_Recursive_Fast_Fourier_Transform_by_Using_AVX-512_SIMD_Instructions). 
CI and BI refer to different ways of memorizing arrays of complex numbers; in the former, real and imaginary parts are interleaved in memory, while in the latter real and imaginary parts are separated in two different regions.
